const TopicsActionTypes = {
  FETCH_TOPICS_START: 'FETCH_TOPICS_START',
  FETCH_TOPICS_SUCCESS: 'FETCH_TOPICS_SUCCESS',
  FETCH_TOPICS_FAILURE: 'FETCH_COLLECTION_FAILURE',
};

export default TopicsActionTypes;
