name: Build Android App

on:
  push:
    branches:
      - master
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn
      - name: Install NDK
        run: |
          echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT} >/dev/null 2>&1
      - name: Setup keystore
        run: |
          echo $SIGNING_KEY | base64 -di > ./android/app/my-upload-key.keystore
        env:
          SIGNING_KEY: ${{ secrets.KEYSTORE_64 }}
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.KEY_PASSWORD }} -PMYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.ALIAS_PASSWORD }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
